### ISSUE TITLE
mod version difference

### ISSUE THREAD

**Issue by schkrisz1** [wolforcept/simpleshops#11]
Dear Developers!

The mod version released on October 31, 2022 was made for an as yet unannounced version. Version 1.19.3 does not even appear, BUT there is not even a snapshot of it.
I would like to ask that you please develop the mod to the correct version, because very few people (compared to the huge download number of 1.16.5 2021 August 19) can download it.

**Comment by ScoutTheSaneless** [comment]
yeah, 1.19.3 isn't quite out yet-

**Comment by schkrisz1** [comment]
Maybe we can expect version 1.19.2?
