### ISSUE TITLE
Two bugs found 

### ISSUE THREAD

**Issue by ThatCraftyTiger** [wolforcept/simpleshops#3]
FIRST BUG: 

      Found out that you can buy custom items with NBT tags on them, from these shops no problem ( buying a sword with a custom name and enchantment). BUT if you say make a currency for players or better example trying to sell a shulker box full of a specific item in exchange for currency, the shop will allow any version of that item even if its not full of the specific item. "So if you wanted players to have to sell a diamond sword with the enchantment smite level 1 and get rewarded with 9 diamonds, a player could cheat and just sell the basic diamond sword and get 9 more diamonds and re-craft the swords!.

SECOND BUG:

     Tested the new update and it seems to not function at all on my server (Only tried the creative shops). Tried using this on a regular world I had on my computer (just made to test the mod) and it crashes the whole game with a tick speed error. Tested to see if it is a mod that I have that is not pairing well by removing all of my mods except for the shops one and it is still not functional. I am unable to use the shops at all both the craftable shop and the creatvie shop.  Tested this on a brand new creative world.

**Comment by wolforcept** [comment]
Please add the error messages and logs that you got when crashing

**Comment by ThatCraftyTiger** [comment]
> Please add the error messages and logs that you got when crashing

Tried to recreate the crash report but I ended up not crashing. I did some testing on my end and it was a different mod crashing my world. Please ignore the bug crash of your mod as it wasnt the issue. 


just in case I ended up getting a crash report when I tried to close the game  Exit Code: -805306369
